site_name: Deep Origin Python client | Deep Origin
site_author: Deep Origin
repo_url: https://github.com/deeporiginbio/deeporigin-client
repo_name: deeporiginbio/deeporigin-client
site_url: https://client-docs.deeporigin.io

docs_dir: 'docs'
theme:
  name: material
  logo: 'images/logo.svg'
  palette:
    primary: custom
  font:
    text: Inter
    code: Roboto Mono
  features:
    - announce.dismiss
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.preview
    - navigation.instant.progress
    - navigation.sections
    - navigation.path
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.suggest
    - toc.follow
  favicon: images/favicon.png
extra_css:
  - stylesheets/extra.css

nav:
- Quickstart:
  - index.md
  - Install: install.md
  - Configure: configure.md
  - Authenticate: how-to/auth.md
- Drug Discovery:
  - Tutorial: 
    - Getting started: dd/tutorial/getting-started.md
    - Docking: dd/tutorial/docking.md
    - ABFE: dd/tutorial/abfe.md
    - RBFE: dd/tutorial/rbfe.md
  - How To:
    - Create a Complex: dd/how-to/complex.md
    - Work with proteins: dd/how-to/proteins.md
    - Prepare proteins: dd/how-to/prepare-protein.md
    - Work with ligands: dd/how-to/ligands.md
    - Visualize proteins and ligands: dd/how-to/visualize.md
    - Filter outputs of Docking: dd/how-to/filter-docking-outputs.md
    - Use outputs of Docking for FEP: dd/how-to/use-docking-outputs-for-fep.md
    - Visualize ABFE trajectories: dd/how-to/visualize-abfe-trajectories.md
  - Reference: 
    - chemistry: dd/ref/chemistry.md
    - structures: dd/ref/structures.md
    - complex: dd/ref/complex.md
    - docking: dd/ref/docking.md
    - abfe: dd/ref/abfe.md
    - rbfe: dd/ref/rbfe.md
- Platform: 
  - platform/index.md
  - How to:
    - Get user information: platform/how-to/user-info.md
    - Get workstation information: platform/how-to/workstation-info.md
  - Refrence:
      - Platform API: platform/ref/platform.md
- Data hub: 
  - data-hub/index.md
  - Deep Origin DataFrames:
    - Tutorial: data-hub/dataframes.md
  - How to:
    - Create objects: data-hub/how-to/create.md
    - Delete objects: data-hub/how-to/delete.md
    - List data: data-hub/how-to/list-data.md
    - View data: data-hub/how-to/view-data.md
    - Upload files: data-hub/how-to/upload-files.md
    - Download files: data-hub/how-to/download-files.md
    - Write data: data-hub/how-to/write-data.md
    - Add data to database: data-hub/how-to/add-data.md
  - API reference:
    - High-level API: data-hub/ref/high-level-api.md
    - Low-level API: data-hub/ref/low-level-api.md
    - Classes & constants: data-hub/ref/types.md
- Compute hub: 
  - compute-hub/index.md
  - How to:
    - Install variables and secrets: compute-hub/how-to/variables.md
    - Get info about your workstation: compute-hub/how-to/workstation-info.md
- Tools: 
  - tools/index.md
  - How to:
    - List tools: tools/how-to/list-tools.md
    - Run tools: tools/how-to/run-tools.md
    - Check tool run status: tools/how-to/check-status.md
    - Wait for a tool run: tools/how-to/wait-for-run.md
  - Available tools:
    - Autodock Vina: tools/vina.md
    - Receptor Prep (PDBFixer): tools/pdbfixer.md
    - Ligand Prep (Meeko): tools/ligand-prep-meeko.md
    - PDB to PDBQT: tools/pdb-to-pdbqt.md
    - Draco: tools/draco.md
  - Reference:
    - Running tools: tools/ref/run.md
    - Utils: tools/ref/utils.md
- Changelog: changelog.md
- Support: https://www.support.deeporigin.com/servicedesk/customer/portals


validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn

use_directory_urls: false

markdown_extensions:
  - tables
  - abbr
  - admonition
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - codehilite
  - footnotes
  - attr_list
  - md_in_html
  - toc:
      permalink: true
      title: Page contents
  - pymdownx.details
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.snippets
  - pymdownx.extra
  - pymdownx.highlight:
      pygments_lang_class: true
  - pymdownx.tabbed:
      alternate_style: true

  
plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: ["."]
          options:   
            annotations_path: brief
            show_source: false
            docstring_options:
              ignore_init_summary: true
            docstring_section_style: table
            heading_level: 2
            inherited_members: true
            merge_init_into_class: false
            separate_signature: true
            show_root_heading: true
            show_root_full_path: true
            show_signature_annotations: true
            signature_crossrefs: true
            show_symbol_type_heading: true
            line_length: 60
            show_signature: true
