site_name: CLI and Python client | Deep Origin
site_author: Deep Origin
repo_url: https://github.com/deeporiginbio/deeporigin-client
repo_name: deeporiginbio/deeporigin-client
site_url: https://client-docs.deeporigin.io

docs_dir: 'docs'
theme:
  name: material
  logo: 'images/logo.svg'
  palette:
    primary: custom
  font:
    text: Inter
    code: Roboto Mono
  features:
    - announce.dismiss
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.preview
    - navigation.instant.progress
    - navigation.sections
    - navigation.path
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.suggest
    - toc.follow
  favicon: images/favicon.png
extra_css:
  - stylesheets/extra.css

nav:
- Quickstart:
  - index.md
  - Install: install.md
  - Configure: configure.md
  - Authenticate: how-to/auth.md
- Platform: 
  - platform/index.md
  - How to:
    - Get user information: how-to/platform/user-info.md
    - Get workstation information: how-to/platform/workstation-info.md
- Data hub: 
  - data-hub/index.md
  - Deep Origin DataFrames:
    - Tutorial: data-hub/dataframes.md
  - How to:
    - Create objects: how-to/data-hub/create.md
    - Delete objects: how-to/data-hub/delete.md
    - List data: how-to/data-hub/list-data.md
    - View data: how-to/data-hub/view-data.md
    - Upload files: how-to/data-hub/upload-files.md
    - Download files: how-to/data-hub/download-files.md
    - Write data: how-to/data-hub/write-data.md
    - Add data to database: how-to/data-hub/add-data.md
  - API reference:
    - High-level API: ref/data-hub/high-level-api.md
    - Low-level API: ref/data-hub/low-level-api.md
    - Classes & constants: ref/data-hub/types.md
- Compute hub: 
  - compute-hub/index.md
  - How to:
    - Install variables and secrets: how-to/compute-hub/variables.md
    - Get info about your workstation: how-to/compute-hub/workstation-info.md
- Changelog: changelog.md
- Support: https://www.support.deeporigin.com/servicedesk/customer/portals


validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn

use_directory_urls: false

markdown_extensions:
  - tables
  - abbr
  - admonition
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - codehilite
  - footnotes
  - attr_list
  - md_in_html
  - toc:
      permalink: true
      title: Page contents
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.snippets
  - pymdownx.extra
  - pymdownx.highlight:
      pygments_lang_class: true
  - pymdownx.tabbed:
      alternate_style: true


plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: ["."]
          options:   
            annotations_path: brief
            show_source: false
            docstring_options:
              ignore_init_summary: true
            docstring_section_style: table
            heading_level: 2
            inherited_members: true
            merge_init_into_class: false
            separate_signature: true
            show_root_heading: true
            show_root_full_path: true
            show_signature_annotations: true
            signature_crossrefs: true
            show_symbol_type_heading: true
            line_length: 60
            show_signature: true
