site_name: Deep Origin Python client | Deep Origin
site_author: Deep Origin
repo_url: https://github.com/deeporiginbio/deeporigin-client
repo_name: deeporiginbio/deeporigin-client
site_url: https://client-docs.deeporigin.io

docs_dir: 'docs'
theme:
  name: material
  logo: 'images/logo.svg'
  palette:
    primary: custom
  font:
    text: Inter
    code: Roboto Mono
  features:
    - announce.dismiss
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.preview
    - navigation.instant.progress
    - navigation.sections
    - navigation.path
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.suggest
    - toc.follow
  favicon: images/favicon.png
extra_css:
  - stylesheets/extra.css


nav:
- Quickstart:
  - index.md
  - Install: install.md
  - Configure: configure.md
  - Authenticate: how-to/auth.md
- Drug Discovery:
  - Tutorial: 
    - Getting started: dd/tutorial/getting-started.md
    - Docking: dd/tutorial/docking.md
    - ABFE: dd/tutorial/abfe.md
    - RBFE: dd/tutorial/rbfe.md
  - How To:
    - Work with a Complex: dd/how-to/complex.md
    - Work with Proteins: dd/how-to/proteins.md
    - Work with Ligands: dd/how-to/ligands.md
    - Visualize proteins and ligands: dd/how-to/visualize.md
    - Find pockets: dd/how-to/find-pockets.md
    - Dock Ligands: dd/how-to/docking.md
    - Filter outputs of Docking: dd/how-to/filter-docking-outputs.md
    - Use outputs of Docking for FEP: dd/how-to/use-docking-outputs-for-fep.md
    - Visualize ABFE trajectories: dd/how-to/visualize-abfe-trajectories.md
    - Job control: dd/how-to/job.md
  - Reference: 
    - chemistry: dd/ref/chemistry.md
    - structures: 
      - Ligand: dd/ref/ligand.md
      - LigandSet: dd/ref/ligandset.md
      - Protein: dd/ref/protein.md
      - Complex: dd/ref/complex.md
      - Pocket: dd/ref/pocket.md
    - docking: dd/ref/docking.md
    - abfe: dd/ref/abfe.md
    - rbfe: dd/ref/rbfe.md
  - Notebooks:
    - Docking: notebooks/docking.html
- Platform: 
  - platform/index.md
  - Tools & Functions:
    - Reference: platform/ref/tools.md
  - Files:
    - Reference: platform/ref/files.md
  - Compute hub: 
    - platform/compute-hub/index.md
    - How to:
      - Install variables and secrets: platform/compute-hub/how-to/variables.md
      - Get info about your workstation: platform/compute-hub/how-to/workstation-info.md
- Developing: 
  - Installing: dev/install.md
  - Clients: dev/clients.md
- Changelog: changelog.md
- Support: https://www.support.deeporigin.com/servicedesk/customer/portals


validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn

use_directory_urls: false

markdown_extensions:
  - tables
  - abbr
  - admonition
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - codehilite
  - footnotes
  - attr_list
  - md_in_html
  - toc:
      permalink: true
      title: Page contents
  - pymdownx.details
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.snippets
  - pymdownx.extra
  - pymdownx.highlight:
      pygments_lang_class: true
  - pymdownx.tabbed:
      alternate_style: true

  
plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: ["."]
          options:   
            annotations_path: brief
            show_source: false
            docstring_options:
              ignore_init_summary: true
            docstring_section_style: table
            heading_level: 2
            inherited_members: true
            merge_init_into_class: false
            separate_signature: true
            show_root_heading: true
            show_root_full_path: true
            show_signature_annotations: true
            signature_crossrefs: true
            show_symbol_type_heading: true
            line_length: 60
            show_signature: true
