site_name: Deep Origin CLI and Python client
site_author: Deep Origin
repo_url: https://github.com/deeporiginbio/deeporigin-client
repo_name: deeporiginbio/deeporigin-client
site_url: https://deeporiginbio.github.io/deeporigin-client/

docs_dir: 'docs'
theme:
  name: material
  logo: 'images/logo.svg'
  palette:
    primary: custom
  font:
    text: Inter
    code: Roboto Mono
  features:
    - announce.dismiss
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.preview
    - navigation.instant.progress
    - navigation.path
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.suggest
    - toc.follow
  favicon: images/favicon.png
extra_css:
  - stylesheets/extra.css

nav:
- Getting started:
  - Overview: index.md
  - Installation: install.md
- How to:
  - Authenticate to Deep Origin: how-to/auth.md
  - Fetch Secrets and Variables: how-to/variables.md
  - View Deep Origin Information: how-to/do-info.md
  - Managed data: 
    - List data: how-to/managed-data/list-data.md
    - Inspect data: how-to/managed-data/inspect-data.md
    - Upload data: how-to/managed-data/upload-data.md
- API reference:
  - Managed data:
    - High-level API: ref/managed-data/high-level-api.md
    - Low-level API: ref/managed-data/low-level-api.md
    - Low-level response schemas: ref/managed-data/low-level-schema.md

validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn

use_directory_urls: false

markdown_extensions:
  - tables
  - abbr
  - admonition
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - codehilite
  - footnotes
  - attr_list
  - md_in_html
  - toc:
      permalink: true
      title: Page contents
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.snippets
  - pymdownx.extra
  - pymdownx.highlight:
      pygments_lang_class: true
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: ["."]
          options:            
            annotations_path: brief
            show_source: false
            docstring_options:
              ignore_init_summary: true
            docstring_section_style: table
            heading_level: 2
            inherited_members: true
            merge_init_into_class: false
            separate_signature: true
            show_root_heading: true
            show_root_full_path: true
            show_signature_annotations: true
            signature_crossrefs: true
            show_symbol_type_heading: true
            line_length: 60
            show_signature: true
