// JS callback that is executed by interactive scatter plot
// generated by bokeh

const x_data = df[x_select.value];
const y_data = df[y_select.value];
const size_data = df[size_select.value];

// Normalize size data for better visualization (e.g., map values to a range)
const min_size = Math.min(...size_data);
const max_size = Math.max(...size_data);

// Define a scaling function for sizes
const sizes = size_data.map(value => {
    return 2 + 15 * (value - min_size) / (max_size - min_size); // Scale sizes between 10 and 40
});

// Update the data source
source.data = { 'x': x_data, 'y': y_data, 'size': sizes };

// Update the axis labels
x_axis.axis_label = x_select.value;
y_axis.axis_label = y_select.value;

// Trigger data change
source.change.emit();

// callback to update selection in database
if (typeof window.deeporigin !== "undefined") {
    var id = source.data['id'][index];
    deeporigin.dataHub.primaryDatabase.selectByRowsAndColumns({ selections: [{ rowId: id }] })
    
}