api_endpoint: https://os.staging.deeporigin.io/api
api_tokens_filename: ~/.deeporigin/api_tokens
auth_audience: https://os.deeporigin.io/api
auth_client_id: 2AMGd2bJnKjMtd7QBvJYlGPqb9vtntsY
auth_client_secret: WNoSHfEIBfM8cSpwhU2k30uGaCD3Uo6KhyklSYsWecrPKHjR9MEdeP3YF094GvZt
auth_device_code_endpoint: oauth/device/code
auth_domain: https://formicbio.us.auth0.com
auth_grant_type: urn:ietf:params:oauth:grant-type:device_code
auth_token_endpoint: oauth/token/
env: staging
feature_flags: null
nucleus_api_route: nucleus-api/api/
organization_id: tools-test
