name: Build Documentation

on:
  pull_request:
    paths:
      - 'docs/**'


jobs:

  build-docs:
    runs-on: ubuntu-latest
    environment:
      name: docs

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: pyproject.toml

      - name: Build docs and check for errors
        run: bash scripts/build_docs.sh
