name: Build Documentation

on:
  pull_request:
    paths:
      - 'docs/**'

jobs:

  build-docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build docs and check for errors
        run: bash scripts/build_docs.sh
