name: Test DO Functions on production

on:
  # Allow manual runs
  workflow_dispatch:

  # Run every day
  schedule:
    - cron: "0 6 * * *"

jobs:
  test-functions-on-production:
    runs-on: ubuntu-latest
    env:
      # Secrets for API and organization
      REFRESH_TOKEN: ${{ secrets.DEEP_ORIGIN_REFRESH_TOKEN }}
      ACCESS_TOKEN: ${{ secrets.DEEP_ORIGIN_ACCESS_TOKEN }}
      DEEP_ORIGIN_ORGANIZATION_ID: ${{ secrets.DEEP_ORIGIN_ORGANIZATION_ID }}
      DEEP_ORIGIN_API_ENDPOINT: ${{ secrets.DEEP_ORIGIN_API_ENDPOINT }}
      DEEP_ORIGIN_NUCLEUS_API_ROUTE: ${{ secrets.DEEP_ORIGIN_NUCLEUS_API_ROUTE }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check API endpoint connectivity
        run: curl -v $DEEP_ORIGIN_API_ENDPOINT || true

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.7.13"
          enable-cache: true

      - name: Set up Python
        run: uv python install

      - name: Install the project
        run: uv sync --all-extras --dev


      - name: Create API Tokens File
        run: |
          mkdir -p ~/.deeporigin
          echo '{
            "refresh": "'$REFRESH_TOKEN'",
            "access": "'$ACCESS_TOKEN'"
          }' > ~/.deeporigin/api_tokens

      - name: Refresh API tokens using deeporigin.auth
        run: |
          uv run scripts/refresh_tokens.py

      - name: Run tests against a live instance
        run: uv run pytest  -s --log-cli-level=ERROR --client default -k functions
