name: Tests against a Live Instance

on:
  # allow manual runs
  workflow_dispatch:

  # run every day
  schedule:
    - cron: "0 0 * * *" 

jobs:
  test-against-live-instance:
    runs-on: ubuntu-latest
    env:
      DEEP_ORIGIN_ORGANIZATION_ID: ${{ secrets.DEEP_ORIGIN_ORGANIZATION_ID }}
      DEEP_ORIGIN_API_ENDPOINT: ${{ secrets.DEEP_ORIGIN_API_ENDPOINT }}
      DEEP_ORIGIN_NUCLEUS_API_ROUTE: ${{ secrets.DEEP_ORIGIN_NUCLEUS_API_ROUTE }}
      DEEP_ORIGIN_ACCESS_TOKEN: ${{ secrets.DEEP_ORIGIN_ACCESS_TOKEN }}


    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        id: cached_python_setup
        with:
          python-version: "3.11"
          cache: 'pip'
          cache-dependency-path: pyproject.toml

      - name: "run tests without ~/.deeporigin/"
        run: |
          pip install --upgrade pip
          pip install --upgrade setuptools
          pip install -e .[test]
          make test-github client=default
