name: Tests against a Live Instance

on:
  # Allow manual runs
  workflow_dispatch:

  # Run every day
  schedule:
    - cron: "0 0 * * *"

jobs:
  write-tokens:
    runs-on: ubuntu-latest
    outputs:
      api_tokens_path: ~/.deeporigin/api_tokens
    steps:
      - name: Create API Tokens File
        run: |
          mkdir -p ~/.deeporigin
          echo '{
            "refresh": "'$DEEP_ORIGIN_REFRESH_TOKEN'",
            "access": "'$DEEP_ORIGIN_ACCESS_TOKEN'"
          }' > ~/.deeporigin/api_tokens
        env:
          DEEP_ORIGIN_REFRESH_TOKEN: ${{ secrets.DEEP_ORIGIN_REFRESH_TOKEN }}
          DEEP_ORIGIN_ACCESS_TOKEN: ${{ secrets.DEEP_ORIGIN_ACCESS_TOKEN }}

  test-against-live-instance:
    runs-on: ubuntu-latest
    needs: write-tokens
    env:
      # Secrets for live instance
      DEEP_ORIGIN_ORGANIZATION_ID: ${{ secrets.DEEP_ORIGIN_ORGANIZATION_ID }}
      DEEP_ORIGIN_API_ENDPOINT: ${{ secrets.DEEP_ORIGIN_API_ENDPOINT }}
      DEEP_ORIGIN_NUCLEUS_API_ROUTE: ${{ secrets.DEEP_ORIGIN_NUCLEUS_API_ROUTE }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        id: cached_python_setup
        with:
          python-version: "3.11"
          cache: 'pip'
          cache-dependency-path: pyproject.toml

      - name: Install dependencies and run tests
        run: |
          pip install --upgrade pip
          pip install --upgrade setuptools
          pip install -e .[test]
          make test-github-live