name: Pre merge checks

on:
  pull_request:
    branches: [ main ]


jobs:

  sonarcloud:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  code-formatting-and-syntax:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4


      - name: Check code formatting using ruff
        uses: chartboost/ruff-action@v1
        with:
          version: 0.3.1
          args: format --check

      - name: Check import order
        uses: chartboost/ruff-action@v1
        with:
          version: 0.3.1
          args: check --select I


  functionality-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]

    needs: [code-formatting-and-syntax]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - run: 'mkdir /home/runner/.deeporigin/'
        shell: bash

      - run: 'cp tests/config.yml /home/runner/.deeporigin/config.yml'
        shell: bash

      - run: 'cp tests/api_tokens /home/runner/.deeporigin/api_tokens'
        shell: bash


      - name: run tests
        run: |
          pip install --upgrade pip
          pip install --upgrade setuptools
          pip install -e .[test]
          make test-github




  

