# Triggered on any push that creates a tag, this workflow builds a source 
# distribution package and uploads it to Python package index. This allows
# users to 'pip install deeporigin'.
name: Publish to PyPI

on:
  push:
    tags:
     - '*'

jobs:
  pypi-publish:
    name: Build and upload release to PyPI
    runs-on: ubuntu-latest
    permissions:
      id-token: write # pypi-publish might need OIDC token to authenticate with PyPI
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install pypa/setuptools
        run: 
          python -m pip install build

      - name: Extract tag name
        id: tag
        # GITHUB_REF contains full reference name, 'refs/tags/v1.0.0, so this 
        # extracts just the tag name (v1.0.0)
        run: echo ::set-output name=TAG_NAME::$(echo $GITHUB_REF | cut -d / -f 3)

      - name: Update version number from tag
        run: >-
          echo "${{ steps.tag.outputs.TAG_NAME }}" > src/VERSION


      - name: Build package
        run: 
          python3 -m build --sdist

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1




