name: publish-to-pypi

on:
  push:
    tags:
     - '*'
  pull_request:
    branches: [ main ]


jobs:
  pypi-publish:
    name: Build and upload release to PyPI
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install pypa/setuptools
        run: 
          python -m pip install build

      - name: Extract tag name
        id: tag
        run: echo ::set-output name=TAG_NAME::$(echo $GITHUB_REF | cut -d / -f 3)

      - name: Update version number from tag
        run: >-
          echo "${{ steps.tag.outputs.TAG_NAME }}" > src/VERSION


      - name: Build package
        run: 
          python3 -m build --sdist



