name: Tools API Tests

on:
  workflow_dispatch:
    inputs:
      env:
        description: "Target environment"
        type: choice
        required: true
        default: prod
        options: [edge, staging,prod]


jobs:
  test:
    # automatically pulls env vars & secrets from the chosen environment
    environment: ${{ inputs.env }}
    runs-on: ubuntu-latest
    env:
      DEEP_ORIGIN_ENV: ${{ inputs.env }}

    
    steps:
      - uses: actions/checkout@v4
      - name: Select API token
        run: |
          if [ "${{ inputs.env }}" = "prod" ]; then
            echo "API_TOKEN=${{ secrets.TOKEN_PROD_ACCESS }}" >> "$GITHUB_ENV"
          elif [ "${{ inputs.env }}" = "staging" ]; then
            echo "API_TOKEN=${{ secrets.TOKEN_STAGING_ACCESS }}" >> "$GITHUB_ENV"
          elif [ "${{ inputs.env }}" = "edge" ]; then
            echo "API_TOKEN=${{ secrets.TOKEN_EDGE_ACCESS }}" >> "$GITHUB_ENV"
          fi
      - uses: actions/setup-python@v5
        with: { python-version: "3.13" }
      - run: pip install .[tools,test,plots]
      - name: Run tests
        run: |
          pytest -v -k test_tools_api --client "default"